import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import Image from 'next/image'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const Filter = ({ filters, activeFilters, onClick }) => {
    return (
        <div className="flex flex-wrap justify-center">
            {filters.map((filter) => (
                <button
                    key={filter}
                    className={`mx-2 my-1 px-3 py-2 text-sm font-semibold 
              ${activeFilters.includes(filter) ? 'bg-black text-white' : 'bg-gray-300 text-gray-600'}
              hover:bg-black-400 hover:text-white focus:bg-black-400 focus:text-white 
              focus:outline-none focus:ring-2 focus:ring-black-500`}
                    onClick={() => onClick(filter)}
                >
                    {filter}
                </button>
            ))}
        </div>
    );
};

export default function Artists() {
    const filters = ["Összes", "Festők", "Szobrászok", "Bútortervezők", "Ékszertervők"];
    const [activeFilters, setActiveFilters] = useState(filters);

    const handleFilter = (filter) => {
        if (filter === "Összes" && activeFilters.length >= 4) {
            clearFilters();
        } else if (filter === "Összes") {
            setActiveFilters(filters)
        } 
        else {
            if (activeFilters.includes(filter)) {
                setActiveFilters(activeFilters.filter((f) => f !== filter));
            } else {
                setActiveFilters([...activeFilters, filter]);
            }
        }
    };

    const clearFilters = () => {
        setActiveFilters([]);
        // add your clear function here
    };

    const ArtistsList = [
        {
            name: 'Leonardo da Vinci',
            avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGxlb25hcmRvJTIwZGElMjB2aW5jaSUyMHBvcnRyYWl0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
        },
        {
            name: 'Vincent van Gogh',
            avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHZpbmNlbnQlMjB2YW4lMjBnb2doJTIwcG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60'
        },
        {
            name: 'Michelangelo Buonarotti',
            avatarUrl: 'https://images.unsplash.com/photo-1601887389937-0b02c26b602c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWljaGVsYW5nZWxvJTIwYnVvbmFycm90aXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60'
        },
        {
            name: 'Salvador Dalí',
            avatarUrl: 'https://images.unsplash.com/photo-1597255131939-1a991e8e00ae?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80'
        },
        {
            name: 'Pablo Picasso',
            avatarUrl: 'https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzR8fHBpY2Fzc28lMjBwb3J0cmFpdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60'
        },
    ]


    return (
        <div>
            <Head>
                <title>mistart - az online auckiós ház</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Hero heading='Művészek' buttonVisible={false} />
            <div className='flex mt-5 justify-center'>
                <Filter filters={filters} activeFilters={activeFilters} onClick={handleFilter} />

            </div>
            <div className='flex flex-wrap justify-center mx-10 mt-20'>
                {ArtistsList.map((artist) => (
                    <div className='flex flex-col items-center mb-10 mx-20'>
                        <div className='relative w-40 h-40 mx-10 mb-10'>
                            <Image
                                src={artist.avatarUrl}
                                fill
                                alt={artist.name}
                                className='rounded-full object-cover'
                            />
                        </div>
                        <div>
                            <h1>{artist.name}</h1>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    )
}
