import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import About from '../components/MainSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>mistart - az online auckiós ház</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero heading='A művészet nem az, amit látsz, hanem amit érzel' buttonText='Éld át a mistart életérzést' buttonVisible={true}/>
      <About/>
    </div>
  )
}
