import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>mystart - az online auckiós ház</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero heading='Magyarország első teljesen online aukciós háza' subHeading='Fiatal művész vagy? Vagy csak imádod a kortárs művészetet? Akkor a legjobb helyen jársz' buttonText='Tudj meg többet'/>
    </div>
  )
}
