import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import About from '@/components/About'
import ServiceCardContainer from '@/components/ServiceCardContainer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>mystart - az online auckiós ház</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero heading='Magyarország első teljesen online aukciós háza' buttonText='Tudj meg többet'/>
      <About/>
      <ServiceCardContainer/>
    </div>
  )
}
